version: 2
project_name: valerie

builds:
  - dir: valerie
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/strawberry-tools/valerie/valerie/cmd.version={{ .Version }} -extldflags "-static"

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}-v{{ .Version }}-{{ if eq .Os "darwin" }}macos{{ else }}{{ .Os }}{{ end }}-{{ .Arch }}{{ if .Arm }}hf{{ end }}
    files:
      - LICENSE
      - README.md

nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    homepage: "https://www.Feliciano.Tech"
    maintainer: "Ricardo N Feliciano <Ricardo@Feliciano.Tech>"
    description: "An HTML schema validator."
    license: MIT
    formats:
      - deb

brews:
  - repository:
      owner: strawberry-tools
      name: homebrew-tap
    commit_author:
      name: "Ricardo N Feliciano (FelicianoTech)"
      email: "Ricardo@Feliciano.Tech"
    directory: Formula
    homepage: "https://github.com/strawberry-tools/valerie"
    description: "An HTML schema validator."
    test: |
      system "#{bin}/valerie", "help"
    install: |-
      bin.install "valerie"
      bash_completion.install "completions/arc.bash" => "valerie"
      fish_completion.install "completions/arc.fish"
      zsh_completion.install "completions/arc.zsh" => "_valerie"

checksum:
  name_template: "{{ .ProjectName }}-v{{ .Version }}-checksums.txt"

announce:
  skip: "{{ gt .Patch 0 }}"
  mastodon:
    enabled: true
    server: "https://nanobyte.cafe"
  mattermost:
    enabled: true
